#!/usr/bin/env bash
# ==============================================================================
# SecLegion OS — Interactive Fastfetch ASCII Logo Showcase (TrueColor)
# ==============================================================================

CYAN="\033[38;2;0;240;255m"
GREEN="\033[38;2;0;255;136m"
WHITE="\033[38;2;255;255;255m"
BOLD="\033[1m"
RESET="\033[0m"

clear
echo -e "${CYAN}${BOLD}====================================================================${RESET}"
echo -e "${GREEN}${BOLD}     SECLEGION OS — FASTFETCH NATIVE ASCII ART SHOWCASE (TRUECOLOR)${RESET}"
echo -e "${CYAN}${BOLD}====================================================================${RESET}\n"

echo -e "${WHITE}${BOLD}[ DESIGN A: The Classic Arch-Style Dot-Gradient Cyber 'S' ]${RESET}"
echo -e "${CYAN}               .---:++ossso+/-."
echo -e "${CYAN}            ./osssssssssssssssss+:."
echo -e "${CYAN}          .+ssssso++/:---:/+ossssss/."
echo -e "${CYAN}         /sssso/.             ./ossss/"
echo -e "${CYAN}        +ssso-                   -osss+"
echo -e "${GREEN}       :ssso'   ':++oooooooo+/-'   '---."
echo -e "${GREEN}       +ssso   -osssssssssssssss+'"
echo -e "${GREEN}       +ssso   osssso:----:/osssso"
echo -e "${GREEN}       :ssso'  :ssss/'      '+ssss:"
echo -e "${GREEN}        +ssso-  ./osssso+:.   ----'"
echo -e "${GREEN}         /sssso/.  '-/+osssso+:.       ${WHITE}󰀄 USER${RESET} aelkholy@A-273"
echo -e "${GREEN}          .+ssssso+:-'   '-/ossss+:    ${GREEN}󰣇 OS${RESET}   SecLegion OS 2026.10"
echo -e "${GREEN}            ./osssssssso+/-'  :ssss+   ${CYAN}󰌽 KER${RESET}  7.2.7 x86_64"
echo -e "${CYAN}               .:/+osssssss+'  +ssso   ${WHITE}󰏗 PKG${RESET}  1330"
echo -e "${CYAN}                    '-/osss+'  +ssso   ${GREEN}󰆍 TERM${RESET} kitty"
echo -e "${CYAN}       '---.           'ssss:  :ssso   ${CYAN}󰞷 SH${RESET}   zsh"
echo -e "${CYAN}      :osss+            +sss+  +ssso   ${WHITE}󰍛 RAM${RESET}  7.6 GiB / 16.0 GiB"
echo -e "${CYAN}      +ssss/           -osss/ :ssso'"
echo -e "${CYAN}      /sssss+:-.....-:+sssso-:osss+"
echo -e "${CYAN}       .+sssssssssssssssss+:ossso:"
echo -e "${CYAN}         ':+osssssssssso+/:ssso-"
echo -e "${CYAN}             '.-://::-.   :oo/.${RESET}\n"

echo -e "${WHITE}${BOLD}[ DESIGN B: The OffSec Razor Shield (Geometric Hacker Blade) ]${RESET}"
echo -e "${CYAN}                   /\\"
echo -e "${CYAN}                  /  \\"
echo -e "${CYAN}                 / /\\ \\"
echo -e "${CYAN}                / /  \\ \\"
echo -e "${GREEN}               / / /\\ \\ \\"
echo -e "${GREEN}              / / /  \\ \\ \\"
echo -e "${GREEN}             / / / /\\ \\ \\ \\            ${WHITE}󰀄 USER${RESET} aelkholy@A-273"
echo -e "${GREEN}            / / / /  \\ \\ \\ \\           ${GREEN}󰣇 OS${RESET}   SecLegion OS 2026.10"
echo -e "${GREEN}           / / / / /\\ \\ \\ \\ \\          ${CYAN}󰌽 KER${RESET}  7.2.7 x86_64"
echo -e "${GREEN}          / / /_/ /  \\ \\_\\ \\ \\         ${WHITE}󰏗 PKG${RESET}  1330"
echo -e "${GREEN}         / /     / /\\ \\     \\ \\        ${GREEN}󰆍 TERM${RESET} kitty"
echo -e "${CYAN}        / /_____/ /  \\ \\_____\\ \\       ${CYAN}󰞷 SH${RESET}   zsh"
echo -e "${CYAN}       /_________/    \\_________\\      ${WHITE}󰍛 RAM${RESET}  7.6 GiB / 16.0 GiB"
echo -e "${CYAN}       \\                         //"
echo -e "${CYAN}        \\   ${GREEN}S E C L E G I O N${CYAN}   //"
echo -e "${CYAN}         \\_____________________//${RESET}\n"

echo -e "${WHITE}${BOLD}[ DESIGN C: The Tactical Cyber Falcon / Razor Wings ]${RESET}"
echo -e "${CYAN}                /\\             /\\"
echo -e "${CYAN}               /  \\___________/  \\"
echo -e "${CYAN}              /   / \\       / \\   \\"
echo -e "${GREEN}             /   /   \\     /   \\   \\"
echo -e "${GREEN}            /   / /\\ \\___/ /\\ \\   \\        ${WHITE}󰀄 USER${RESET} aelkholy@A-273"
echo -e "${GREEN}           /   /_/  \\_   _/  \\_\\   \\       ${GREEN}󰣇 OS${RESET}   SecLegion OS 2026.10"
echo -e "${GREEN}          /            \\_/            \\      ${CYAN}󰌽 KER${RESET}  7.2.7 x86_64"
echo -e "${GREEN}         /________   __     __   ________\\     ${WHITE}󰏗 PKG${RESET}  1330"
echo -e "${CYAN}                 \\  \\ \\   / /  /             ${GREEN}󰆍 TERM${RESET} kitty"
echo -e "${CYAN}                  \\  \\ \\_/ /  /              ${CYAN}󰞷 SH${RESET}   zsh"
echo -e "${CYAN}                   \\  \\___/  /               ${WHITE}󰍛 RAM${RESET}  7.6 GiB / 16.0 GiB"
echo -e "${CYAN}                    \\        /"
echo -e "${CYAN}                     \\______/"
echo -e "${WHITE}                  [ S E C L E G I O N ]${RESET}\n"

echo -e "${WHITE}${BOLD}[ DESIGN D: The Glitched Circuit Hex (Arch Dot Texture) ]${RESET}"
echo -e "${CYAN}                   .o+'''''+o."
echo -e "${CYAN}                .+oo'       'oo+."
echo -e "${CYAN}              .+oo'   .---.   'oo+."
echo -e "${GREEN}             /oo/    /     \\    /oo/"
echo -e "${GREEN}            |oo|    |   ${WHITE}S${GREEN}   |    |oo|           ${WHITE}󰀄 USER${RESET} aelkholy@A-273"
echo -e "${GREEN}            |oo|     \\     /    |oo|           ${GREEN}󰣇 OS${RESET}   SecLegion OS 2026.10"
echo -e "${GREEN}             \\oo\\     '---'    /oo/            ${CYAN}󰌽 KER${RESET}  7.2.7 x86_64"
echo -e "${GREEN}              '+oo.           .oo+'             ${WHITE}󰏗 PKG${RESET}  1330"
echo -e "${CYAN}                '+oo.       .oo+'               ${GREEN}󰆍 TERM${RESET} kitty"
echo -e "${CYAN}                   'o+.....+o'                  ${CYAN}󰞷 SH${RESET}   zsh"
echo -e "${WHITE}                SECLEGION OFFSEC${RESET}\n"

echo -e "${CYAN}====================================================================${RESET}"
echo -e " Run ${GREEN}${BOLD}./preview_ascii_logos.sh${RESET} in any terminal tab to see them live!"
echo -e "${CYAN}====================================================================${RESET}"
