# ==============================================================================
# Calamares Post-Install Script — AE_ARCH by Ammar Elkholy
# Solves user permissions, systemd service enablement & PGP keyring
# ==============================================================================
---
dontChroot: false
timeout: 180
script:
    - "-pacman-key --init"
    - "-pacman-key --populate archlinux"
    - "-chown -R 1000:1000 /home/*"
    - "-systemctl enable gdm.service"
    - "-systemctl enable NetworkManager.service"
    - "-systemctl enable bluetooth.service"
