# ==============================================================================
# Calamares Post-Install Script — SecLegion OS by Ammar Elkholy
# Solves user permissions, systemd service enablement & PGP keyring
# ==============================================================================
---
dontChroot: false
timeout: 180
script:
    - "-pacman-key --init"
    - "-pacman-key --populate archlinux"
    - "-chown -R 1000:1000 /home/*"
    - "-systemctl enable gdm.service"
    - "-systemctl enable NetworkManager.service"
    - "-systemctl enable bluetooth.service"
    - "-systemctl enable libvirtd.service"
    - "-systemctl enable virtlogd.service"
    - "-usermod -aG libvirt,kvm,wireshark,wheel $(id -nu 1000 2>/dev/null || echo liveuser)"
    - "-timedatectl set-local-rtc 1 --adjust-system-clock"
